### ISSUE TITLE
I need help sir

### ISSUE THREAD

**Issue by KevinNitroG** [AKhilRaghav0/Rewards_VPS#1]
I have run the code and it failed
Here is the log:

```
[LOGS] "logs.txt" file not found.
[LOGS] "logs.txt" created.

******************hiden******************

[WDM] - Downloading:   0%|          | 0.00/6.96M [00:00<?, ?B/s]
[WDM] - Downloading: 100%|██████████| 6.96M/6.96M [00:00<00:00, 111MB/s]
[LOGIN] Logging-in...


Traceback (most recent call last):
  File "/home/runner/work/Rewards_VPS/Rewards_VPS/MicrosoftRewardsBot.py", line 1639, in farmer
    login(browser, account['username'], account['password'])
  File "/home/runner/work/Rewards_VPS/Rewards_VPS/MicrosoftRewardsBot.py", line 1[7](**hiden**)7, in login
    browser.get('https://login.live.com/')
AttributeError: 'NoneType' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/Rewards_VPS/Rewards_VPS/MicrosoftRewardsBot.py", line 1767, in <module>
    main()
  File "/home/runner/work/Rewards_VPS/Rewards_VPS/MicrosoftRewardsBot.py", line 1754, in main
    farmer()
  File "/home/runner/work/Rewards_VPS/Rewards_VPS/MicrosoftRewardsBot.py", line 17[10](https://github.com/KevinNitroG/Rewards_VPS/actions/runs/4152170634/jobs/7182951699#step:5:11), in farmer
    browser.quit()
AttributeError: 'NoneType' object has no attribute 'quit'
Error: Process completed with exit code 1.
```

**Comment by AKhilRaghav0** [comment]
running Rewards_VPS over github Runner, if using any custom-made .yml then mention it in comments.
+ install google-chrome-stable

**Comment by KevinNitroG** [comment]
```
name: Code

on:
   workflow_dispatch:
   workflow_run:
    workflows: Build
    branches: [main]
   push:
    branches:
      - main
  #schedule:
  #- cron: "0 */12 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        
      - name: Install Python requirements
      # You may pin to the exact commit or the version.
      # uses: aabadie/action-install-python-requirements@bd1357189566c9678a47677d561b4b8e113d9787
        uses: aabadie/action-install-python-requirements@v2.0.1
        with:
          # requirements text file
          requirements: requirements.txt
          # Whether pip also has to be updated
          # update-pip:
      - name: Install Chrome
      
        # You may pin to the exact commit or the version.
        # uses: logikal-io/install-chrome@074db03e25b1b5d42838b25dcca9b895450e4185
        uses: logikal-io/install-chrome@v1.0.1
        with:
          # The version to install (exactly as in https://www.ubuntuupdates.org/package/google_chrome/stable/main/base/google-chrome-stable)
          version: 109.0.5414.119-1
          
      - name: Setup Chrome
        # You may pin to the exact commit or the version.
        # uses: browser-actions/setup-chrome@d3406b80ca1210f7eb78c86b9abe29d1961f9a49
        uses: browser-actions/setup-chrome@v1.0.1
        with:
          # The Google Chrome/Chromium version to install and use.
          chrome-version: latest
          
      - name: Run Python code
        run:
         python3
         MicrosoftRewardsBot.py --headless --fast --session
```

Here it is.

**Comment by AKhilRaghav0** [comment]
Why install chrome, when it already exists in the runner image of ubuntu-latest
```
steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
       pip install -r requirements.txt
```
+ NO need to install Requirements like that.

**Comment by AKhilRaghav0** [comment]
**And add one more thing**
```

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 40
```

Add _timeout-minutes_ up to 40, it will terminate Workflow if it exceeds 40min runtime.

**Comment by KevinNitroG** [comment]
Thank you 😅 I will try it. This is the first time I have used github workflow 🙄🙄

**Comment by AKhilRaghav0** [comment]
> Thank you sweat_smile I will try it. This is the first time I have used github workflow roll_eyesroll_eyes

Next time use the Discussion Section :grin:

**Comment by KevinNitroG** [comment]
I got error like this. Do I have to cd up for a multiple folders?

![Screenshot_2023-02-14-11-29-44-458-edit_com android chrome](https://user-images.githubusercontent.com/86353526/218639735-afa6bf17-cb24-44e4-8cd0-b4b7e6a455bc.jpg)

This is my code now:

```
name: Code

on:
   workflow_dispatch:
   workflow_run:
    workflows: Build
    branches: [main]
   push:
    branches:
      - main
  #schedule:
  #- cron: "0 */12 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
    
      - name: Run Python code
        run:
         python3
         MicrosoftRewardsBot.py --fast

```

**Comment by AKhilRaghav0** [comment]
Add 
```yml
Permissions:
   contents: read
```
![image](https://user-images.githubusercontent.com/86706467/218643494-75ab3756-62ce-44c9-8307-461e3e07778e.png)

**Comment by KevinNitroG** [comment]
I still got a error 😢 Sorry for having bothered you so much.

![Screenshot_2023-02-14-12-45-12-194-edit_com android chrome](https://user-images.githubusercontent.com/86353526/218650038-5336e668-af08-4854-87a9-9809a1032394.jpg)

**Comment by AKhilRaghav0** [comment]
> I still got a error cry Sorry for having bothered you so much.
> 
> ![Screenshot_2023-02-14-12-45-12-194-edit_com android chrome](https://user-images.githubusercontent.com/86353526/218650038-5336e668-af08-4854-87a9-9809a1032394.jpg)

It's okay man, can we shift to the discussion?
https://github.com/AKhilRaghav0/Rewards_VPS/discussions

**Comment by KevinNitroG** [comment]
I will shift to the discussion later ((: 😁
